language: 'ko-KR'
  high_level_summary: true
early_access: false
reviews:
  profile: 'chill'
  request_changes_workflow: false
  poem: true
  review_status: true
  collapse_walkthrough: false
  path_filters: ['!.github/**', '!dist/**', '!./**']
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true
